require('user.plugins_configs.bufferline')
require('user.plugins_configs.floaterm')
require('user.plugins_configs.gitsigns')
require('user.plugins_configs.blame')
-- require('user.plugins_configs.indent_blankline')
require('user.plugins_configs.lsp_saga')
require('user.plugins_configs.lualine')
require('user.plugins_configs.material')
require('user.plugins_configs.minimap')
require('user.plugins_configs.misc')
require('user.plugins_configs.neoclip')
-- temporarily swithced neoscroll off
-- require('user.plugins_configs.neoscroll')
require('user.plugins_configs.neotest')
require('user.plugins_configs.nvim_tree')
require('user.plugins_configs.nvim_ufo')
require('user.plugins_configs.startify')
require('user.plugins_configs.telescope')
require('user.plugins_configs.telescope_grep')
require('user.plugins_configs.todo')
require('user.plugins_configs.treesitter')
require('user.plugins_configs.trouble')
require('user.plugins_configs.ts_autotag')
-- require('user.plugins_configs.solar_client')
-- winbar requires NeoVim nightly, aka 0.9.x
-- require('user.plugins.winbar')

